
const Texts = {
    español: {
        menuHome: 'Home',
        menuProyects: 'Proyectos',
        menuContact: 'Contacto',
        ProjectDescription: 'Descripción:',
        ProjectRepository: 'Repositorio',
        ProjectLink: 'Ver Proyecto',
        NonogramTitle: 'Nonograma (Juego)',
        Nonogram1: 'Juego de lógica multi-nivel creado con ',
        Nonogram2: '#ReactJS ',
        Nonogram3: ' y desarrollado a petición de #Page 64 junto con otros juegos para incluirlo en la sección de entretenimiento del periódico ',
        Nonogram4: '#La Vanguardia ',
        Nonogram5: ' de Barcelona.',
        OneToFiftyTitle: 'One To Fifty (Juego)',
        OneToFifty1: 'Juego de agudeza y rapidez visual creado con ',
        OneToFifty2: '#ReactJS ',
        OneToFifty3: ' y desarrollado a petición de #Page 64 junto con otros juegos para incluirlo en la sección de entretenimiento del periódico ',
        OneToFifty4: '#La Vanguardia ',
        OneToFifty5: 'de Barcelona. Sé el más rápido en completar la secuencia desde el 1 hasta el 50. ¡Cada milésima cuenta!',
        LaVanguardiaTitle: 'Seccion de entretenimiento de La Vanguardia',
        LaVanguardia1: 'Seccion de juegos realizada para el peródico de ',
        LaVanguardia2: '#La Vanguardia ',
        LaVanguardia3: 'desarrollada en tres meses con ',
        LaVanguardia4: '#React ',
        LaVanguardia5: ', #Node ',
        LaVanguardia6: ' y ',
        LaVanguardia7: '#MySql ',
        LaVanguardia8: ' . El proyecto incluye tanto una sección propia de juegos de entretenimiento, como la inserción de iframes customizables en la portada de cada sección del periódico. Además de una página de registro / login donde gestionar tu cuenta personal y tu ranking.',
        FilmsTitle: 'Filmoteca',
        Films: 'Emulador de videoclub donde podrás buscar peliculas y filtrarlas por géneros, añadirlas a tu lista de favoritos o escoger una al azar.',
        MasterMindQuizzTitle: 'Quizz (Juego)',
        MasterMindQuizz1: 'Juego de preguntas y respuestas creado con ',
        MasterMindQuizz2: '#VanillaJS ',
        MasterMindQuizz3: '#HTML ',
        MasterMindQuizz4: ' y ',
        MasterMindQuizz5: ' #CSS. ',
        MasterMindQuizz6: ' Contesta bien todas las posibles y consigue puntos.',
        OpenTriviaTitle: 'Open Trivia (Juego)',
        OpenTrivia1: 'Versión mejorada del juego Master Mind Quizz creado con ',
        OpenTrivia2: '#ReactJS ',
        OpenTrivia3: ' en la que trabajamos con la ',
        OpenTrivia4: '#API ',
        OpenTrivia5: 'Open Trivia DB.Selecciona la categoría, la dificultad y el numero de preguntas e intenta conseguir el máximo numero de puntos posible.Tranquilo, al final podrás ver las respuestas correctas.',
        OpenTrivia6:'Open Trivia DB.Selecciona la categoría, la dificultad y el numero de preguntas e intenta conseguir el máximo numero de puntos posible.',
        LaPajitaTitle: 'Gestión de listas de espera dinámicas de locales',
        LaPajita1: 'Web app realizada durante el EU Hackathon de #WCS para la startup #LaPajita, encargada de gestionar la lista de espera de los bares, su ubicación, carta, opiniones y mucho más, realizada con',
        LaPajita2: '#ReactJS ',
        LaPajita3: ' y ',
        LaPajita4: '#NodeJS ',
        LaPajita5: ' para el backend.',
        PanicFridgeTitle: 'Panic Fridge',
        PanicFridge1: 'Web app para descubrir las mejores recetas.Podrás escoger en función de lo que tengas en la nevera.Realizada con ',
        PanicFridge2: '#ReactJS ',
        PanicFridge3: 'y ',
        PanicFridge4: ' #API Rest.',
        OneSearchTitle: 'One Search',
        OneSearch1: ' Una aplicacion para buscar y comparar información de Twitter, Wikipedia y Wikipedia-imágenes. Realizada con ',
        OneSearch2: '#ReactJS ',
        OneSearch3: 'y ',
        OneSearch4: ' #API Rest.',
        Contactdirection: 'Palma de Mallorca, España',
        ContactCV: 'Descarga CV.Pdf',
        DemoTypedText: ["Soy... <strong><span style='color:#ffb510'> curioso</span></strong>","Me encanta... <strong>aprender<span style='color:#ffb510'> cosas nuevas</span></strong>", "Soy... <strong><span style='color:#ffb510'>trabajador</span></strong> y muy<strong><span style='color:#ffb510'> detallista.</span></strong>"] 
       
    },
    english: {
        menuHome: 'Home',
        menuProyects: 'Projects',
        menuContact: 'Contact',
        ProjectDescription: 'Description:',
        ProjectRepository: 'Repository',
        ProjectLink: 'View project',
        NonogramTitle: 'Nonogram (Game)',
        Nonogram1: 'Multi-level logic game created with ',
        Nonogram2: '#ReactJS ',
        Nonogram3: ' and developed at the request of Page 64 along with other games for inclusion in the entertainment section of ',
        Nonogram4: '#La Vanguardia ',
        Nonogram5: ' newspaper in Barcelona.',
        OneToFiftyTitle: 'One To Fifty (Game)',
        OneToFifty1: 'A game of visual sharpness and speed created with ',
        OneToFifty2: '#ReactJS ',
        OneToFifty3: ' and developed at the request of Page 64 along with other games for inclusion in the entertainment section of the',
        OneToFifty4: '#La Vanguardia ',
        OneToFifty5: ' newspaper in Barcelona. Be the fastest to complete the sequence from 1 to 50. Every thousandth counts!',
        LaVanguardiaTitle: 'Game section for La Vanguardia newspaper',
        LaVanguardia1: 'Game section developed for ',
        LaVanguardia2: '#La Vanguardia ',
        LaVanguardia3: 'newspaper in three months with ',
        LaVanguardia4: '#React ',
        LaVanguardia5: ', #Node ',
        LaVanguardia6: ' and ',
        LaVanguardia7: '#MySql ',
        LaVanguardia8: ' . The project includes both a section of entertainment games, as the insertion of customizable iframes on the cover of each section of the newspaper. In addition to a login page where you can manage your personal account and your ranking.',
        FilmsTitle: 'Films discover',
        Films: 'Video store emulator where you can search for movies and filter them by genres, add them to your list of favorites or choose one at random.',
        MasterMindQuizzTitle: 'Quizz (Game)',
        MasterMindQuizz1: 'Question and answer game created with ',
        MasterMindQuizz2: '#VanillaJS ',
        MasterMindQuizz3: ' #HTML',
        MasterMindQuizz4: ' and ',
        MasterMindQuizz5: ' #CSS',
        MasterMindQuizz6: '. Answer all possible questions well and get points.',
        OpenTriviaTitle: 'Open Trivia (Game)',
        OpenTrivia1: 'Improved version of the Master Mind Quizz game created with ',
        OpenTrivia2: '#ReactJS ',
        OpenTrivia3: '  in which we work with the Open Trivia DB ',
        OpenTrivia4: '#API ',
        OpenTrivia5: "Select the category, the difficulty and the number of questions and try to get as many points as possible. Don't worry, you'll get the right answers in the end.",
        OpenTrivia6: 'Select the category, the difficulty and the number of questions and try to get as many points as possible.',
        LaPajitaTitle: 'Dynamic waiting list management',
        LaPajita1: 'Web app made during the EU Hackathon of #WCS for the startup #LaPajita, with which you can manage the waiting list of the bars, their location, menu, opinions and much more, made with ',
        LaPajita2: '#ReactJS ',
        LaPajita3: ' and ',
        LaPajita4: '#NodeJS ',
        LaPajita5: ' for the backend.',
        PanicFridgeTitle: 'Panic Fridge',
        PanicFridge1: 'Web app to discover the best recipes. You can choose according to what you have in the fridge. Made with ',
        PanicFridge2: '#ReactJS ',
        PanicFridge3: 'and ',
        PanicFridge4: ' #API Rest.',
        OneSearchTitle: 'One Search',
        OneSearch1: 'An application to search and compare information from Twitter, Wikipedia and Wikipedia-images. Made with ',
        OneSearch2: '#ReactJS ',
        OneSearch3: 'and ',
        OneSearch4: ' #API Rest.',
        Contactdirection: 'Palma de Mallorca, Spain.',
        ContactCV: 'Download CV.Pdf',
        DemoTypedText: ["I... <strong>am <span style='color:#ffb510'>curious</span></strong>", "I... <strong>love learning <span style='color:#ffb510'>new things</span></strong>", "I... <strong>am <span style='color:#ffb510'>hard</span> worker</strong>", "I... <strong>am <span style='color:#ffb510'>very detailed</span></strong>"] 
    }
}

const getText=(idioma,frase)=>{
    return(
        Texts[idioma][frase]
    );
}

export default getText;